export const CLASSIFICATIONS = {
  INDUSTRIAL_FIRE: 'Industrial Fire',
  GAS_FLARE: 'Gas Flare',
  PERSISTENT_HEAT: 'Persistent Industrial Heat',
  OTHER_THERMAL: 'Other Thermal Source',
}

export const CLASS_COLORS = {
  [CLASSIFICATIONS.INDUSTRIAL_FIRE]: {
    bg: '#ef4444',
    border: '#dc2626',
    text: '#fee2e2',
    pillBg: 'rgba(239, 68, 68, 0.15)',
    glow: 'rgba(239, 68, 68, 0.5)',
    icon: 'Flame',
    tag: 'CRITICAL HAZARD',
  },
  [CLASSIFICATIONS.GAS_FLARE]: {
    bg: '#f97316',
    border: '#ea580c',
    text: '#ffedd5',
    pillBg: 'rgba(249, 115, 22, 0.15)',
    glow: 'rgba(249, 115, 22, 0.5)',
    icon: 'Radio',
    tag: 'CONTINUOUS FLARE',
  },
  [CLASSIFICATIONS.PERSISTENT_HEAT]: {
    bg: '#3b82f6',
    border: '#2563eb',
    text: '#dbeafe',
    pillBg: 'rgba(59, 130, 246, 0.15)',
    glow: 'rgba(59, 130, 246, 0.5)',
    icon: 'Factory',
    tag: 'CHRONIC SOURCE',
  },
  [CLASSIFICATIONS.OTHER_THERMAL]: {
    bg: '#64748b',
    border: '#475569',
    text: '#f1f5f9',
    pillBg: 'rgba(100, 116, 139, 0.15)',
    glow: 'rgba(100, 116, 139, 0.3)',
    icon: 'Activity',
    tag: 'RURAL / STUBBLE',
  },
}

export const RISK_LEVELS = {
  CRITICAL: {
    label: 'CRITICAL',
    color: '#ef4444',
    bg: 'rgba(239, 68, 68, 0.15)',
    border: 'rgba(239, 68, 68, 0.4)',
    scoreRange: '75 – 100',
    priority: 'Immediate Emergency Response',
    actionDesc: 'Immediate alert dispatched to GIDC Disaster Cell and Fire Services.',
  },
  HIGH: {
    label: 'HIGH',
    color: '#f97316',
    bg: 'rgba(249, 115, 22, 0.15)',
    border: 'rgba(249, 115, 22, 0.4)',
    scoreRange: '50 – 75',
    priority: 'High Priority Inspection',
    actionDesc: 'Priority surveillance and industrial emission verification required.',
  },
  MODERATE: {
    label: 'MODERATE',
    color: '#f59e0b',
    bg: 'rgba(245, 158, 11, 0.15)',
    border: 'rgba(245, 158, 11, 0.4)',
    scoreRange: '25 – 50',
    priority: 'Routine Watchlist Monitoring',
    actionDesc: 'Logged into persistent industrial thermal surveillance catalog.',
  },
  LOW: {
    label: 'LOW',
    color: '#10b981',
    bg: 'rgba(16, 185, 129, 0.15)',
    border: 'rgba(16, 185, 129, 0.4)',
    scoreRange: '0 – 25',
    priority: 'Baseline Agricultural / Rural',
    actionDesc: 'No emergency action needed; non-industrial baseline thermal signature.',
  },
}

export const SHAP_FEATURE_DESCRIPTIONS = {
  bright_ti4: {
    label: 'VIIRS TI4 Brightness (MWIR)',
    unit: 'K',
    judgeExplanation: 'Mid-wave IR brightness temperature; values > 320K indicate intense thermal combustion.',
  },
  bright_ti5: {
    label: 'VIIRS TI5 Brightness (LWIR)',
    unit: 'K',
    judgeExplanation: 'Long-wave IR brightness temperature for background ambient calibration.',
  },
  delta_t: {
    label: 'Combustion Contrast (ΔT)',
    unit: 'K',
    judgeExplanation: 'Temperature difference (TI4 - TI5); high values prove sub-pixel combustion.',
  },
  frp: {
    label: 'Fire Radiative Power',
    unit: 'MW',
    judgeExplanation: 'Instantaneous thermal energy output in megawatts.',
  },
  distance_to_industry: {
    label: 'Distance to Industry Boundary',
    unit: 'm',
    judgeExplanation: 'Physical distance to registered GIDC/OSM industrial landuse boundary.',
  },
  industries_within_500m: {
    label: 'Facilities within 500m',
    unit: 'count',
    judgeExplanation: 'Direct industrial density in immediate 500m perimeter.',
  },
  industries_within_1km: {
    label: 'Facilities within 1km',
    unit: 'count',
    judgeExplanation: 'Industrial clustering count in 1km radius.',
  },
  industries_within_2km: {
    label: 'Facilities within 2km',
    unit: 'count',
    judgeExplanation: 'Regional industrial zone concentration.',
  },
  cluster_span_days: {
    label: 'Cluster Temporal Span',
    unit: 'days',
    judgeExplanation: 'Observation span duration; proves chronic operational persistence.',
  },
  cluster_event_count: {
    label: 'Cluster Detection Count',
    unit: 'events',
    judgeExplanation: 'Cumulative satellite detections at this exact hot-spot site.',
  },
  cluster_unique_dates: {
    label: 'Unique Observation Dates',
    unit: 'days',
    judgeExplanation: 'Number of separate days the satellite recorded thermal anomalies.',
  },
  daynight: {
    label: 'Day / Night Overpass',
    unit: 'flag',
    judgeExplanation: 'Night passes (0) eliminate solar glint, confirming genuine hot-spots.',
  },
  NDVI: {
    label: 'Sentinel-2 Vegetation Index',
    unit: 'index',
    judgeExplanation: 'Low NDVI indicates absence of dense vegetation (urban/industrial surface).',
  },
  NDBI: {
    label: 'Sentinel-2 Built-Up Index',
    unit: 'index',
    judgeExplanation: 'Positive NDBI indicates concrete/metal industrial infrastructure.',
  },
  NDWI: {
    label: 'Sentinel-2 Water Index',
    unit: 'index',
    judgeExplanation: 'Water index to eliminate shoreline glint / cooling pond reflections.',
  },
}

export const PREDICTION_PRESETS = [
  {
    name: 'Sanand Flare Stack Candidate',
    description: 'High FRP, moderate distance to factory, recurring night detections',
    data: {
      event_id: 'PRESET_FLARE_01',
      bright_ti4: 352.4,
      bright_ti5: 301.2,
      frp: 9.8,
      delta_t: 51.2,
      daynight: 0,
      distance_to_industry: 420.0,
      industries_within_500m: 1,
      industries_within_1km: 4,
      industries_within_2km: 11,
      NDVI: 0.14,
      NDBI: 0.18,
      NDWI: -0.28,
      cluster_event_count: 8,
      cluster_unique_dates: 7,
      cluster_span_days: 34,
    },
  },
  {
    name: 'Vatva Industrial Fire Outbreak',
    description: 'Extreme thermal spike (FRP 24.5 MW, ΔT 68K) right inside chemical cluster',
    data: {
      event_id: 'PRESET_FIRE_EMERGENCY',
      bright_ti4: 368.5,
      bright_ti5: 300.5,
      frp: 24.5,
      delta_t: 68.0,
      daynight: 0,
      distance_to_industry: 45.0,
      industries_within_500m: 5,
      industries_within_1km: 12,
      industries_within_2km: 26,
      NDVI: 0.08,
      NDBI: 0.28,
      NDWI: -0.35,
      cluster_event_count: 2,
      cluster_unique_dates: 1,
      cluster_span_days: 0,
    },
  },
  {
    name: 'Chhatral Chronic Kiln / Smelter',
    description: 'Low-to-moderate FRP but continuous 80+ day detection span',
    data: {
      event_id: 'PRESET_PERSISTENT_KILN',
      bright_ti4: 312.8,
      bright_ti5: 296.1,
      frp: 2.1,
      delta_t: 16.7,
      daynight: 0,
      distance_to_industry: 180.0,
      industries_within_500m: 2,
      industries_within_1km: 6,
      industries_within_2km: 15,
      NDVI: 0.19,
      NDBI: 0.12,
      NDWI: -0.30,
      cluster_event_count: 24,
      cluster_unique_dates: 19,
      cluster_span_days: 78,
    },
  },
  {
    name: 'Rural Agricultural Stubble Burn',
    description: 'High day FRP, 6+ km from any industrial polygon, single-day burst',
    data: {
      event_id: 'PRESET_RURAL_FIELD',
      bright_ti4: 338.0,
      bright_ti5: 305.0,
      frp: 6.2,
      delta_t: 33.0,
      daynight: 1,
      distance_to_industry: 6200.0,
      industries_within_500m: 0,
      industries_within_1km: 0,
      industries_within_2km: 0,
      NDVI: 0.52,
      NDBI: -0.22,
      NDWI: -0.55,
      cluster_event_count: 1,
      cluster_unique_dates: 1,
      cluster_span_days: 0,
    },
  },
]
